name: Run tests
on:
  push:

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Build and run tests
        run: |
          npm i
          npm run build
          npm run test
